#!/usr/bin/env bash
# cl-wire-audit.sh — Detect "80% built, never wired" gaps in LOOP infrastructure.
#
# TYPE A (Missing Wire): hook/script exists but is not in base.json execution chain.
# TYPE B (Broken Loop): producer writes file X, consumer reads file Y (schema mismatch).
#
# Usage:
#   bash scripts/cl-wire-audit.sh              # Full audit (Type A + B)
#   bash scripts/cl-wire-audit.sh --type-a     # Wire coverage only
#   bash scripts/cl-wire-audit.sh --type-b     # I/O contract only
#   bash scripts/cl-wire-audit.sh --json       # JSON output for CI
#
# Exit code: 0 = no gaps, 1 = gaps found (CI gate)
# Opt-out: LOOP_WIRE_AUDIT=0 (disables all checks)
#
# Exemptions: hooks/exempt.txt lists hooks intentionally not in base.json.
# Each line: "filename.sh  # reason"

set -euo pipefail

[[ "${LOOP_WIRE_AUDIT:-1}" == "0" ]] && exit 0

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASE_JSON="$REPO_ROOT/hooks/base.json"
EXEMPT_FILE="$REPO_ROOT/hooks/exempt.txt"
IO_CONTRACTS="$REPO_ROOT/scripts/cl-io-contracts.txt"

# ── Argument parsing ────────────────────────────────────────────────────────
CHECK_TYPE_A=true
CHECK_TYPE_B=true
JSON_OUTPUT=false

DISCOVER_MODE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --type-a)   CHECK_TYPE_A=true; CHECK_TYPE_B=false; shift ;;
    --type-b)   CHECK_TYPE_A=false; CHECK_TYPE_B=true; shift ;;
    --json)     JSON_OUTPUT=true; shift ;;
    --discover) DISCOVER_MODE=true; shift ;;
    -h|--help)
      echo "Usage: cl-wire-audit.sh [--type-a] [--type-b] [--json] [--discover]"
      echo "  --type-a    Check hook wiring coverage only"
      echo "  --type-b    Check I/O contract coverage only"
      echo "  --json      Output JSON for CI parsing"
      echo "  --discover  Auto-scan source files and print a draft cl-io-contracts.txt"
      exit 0 ;;
    *) shift ;;
  esac
done

# ── Discover mode: auto-generate contracts from source grep ──────────────────
if [[ "$DISCOVER_MODE" == "true" ]]; then
  echo "# cl-io-contracts.txt — AUTO-GENERATED by cl-wire-audit.sh --discover"
  echo "# Review carefully before committing. Add missing entries manually."
  echo "# FORMAT: SCRIPT  WRITES|READS  relative/path/to/file"
  echo ""

  # Find all WRITES (append to .jsonl files)
  echo "# ── WRITES (producers) ─────────────────────────────────────────────"
  grep -rn '>>[[:space:]]*"*\$\?[A-Za-z_]*FILE\|>> .*\.jsonl' \
    "$REPO_ROOT/scripts/" "$REPO_ROOT/hooks/" 2>/dev/null \
  | grep -v '\.pyc\|#' \
  | while IFS=: read -r filepath lineno content; do
      script=$(realpath --relative-to="$REPO_ROOT" "$filepath" 2>/dev/null || echo "$filepath")
      path=$(echo "$content" | grep -oE '[A-Z_]*FILE|[a-z._/-]*\.jsonl' | head -1)
      [[ -n "$path" ]] && echo "$script  WRITES  $path"
    done | sort -u

  echo ""
  echo "# ── READS (consumers) ──────────────────────────────────────────────"
  grep -rn 'cat[[:space:]]\+.*\.jsonl\|jq.*\.jsonl\|open.*\.jsonl\|python3.*\.jsonl' \
    "$REPO_ROOT/scripts/" "$REPO_ROOT/hooks/" 2>/dev/null \
  | grep -v '\.pyc\|#' \
  | while IFS=: read -r filepath lineno content; do
      script=$(realpath --relative-to="$REPO_ROOT" "$filepath" 2>/dev/null || echo "$filepath")
      path=$(echo "$content" | grep -oE '[a-z._/-]*\.jsonl' | head -1)
      [[ -n "$path" ]] && echo "$script  READS  $path"
    done | sort -u

  exit 0
fi

# ── Counters ─────────────────────────────────────────────────────────────────
TYPE_A_GAPS=()
TYPE_A_DANGLING=()
TYPE_B_GAPS=()
WARNINGS=()

# ── Type A: Wire coverage ────────────────────────────────────────────────────

if [[ "$CHECK_TYPE_A" == "true" ]]; then

  [[ ! -f "$BASE_JSON" ]] && { echo "[wire-audit] SKIP: base.json not found at $BASE_JSON"; exit 0; }

  # Build exempt set (hooks intentionally not wired)
  EXEMPT_SET=()
  if [[ -f "$EXEMPT_FILE" ]]; then
    while IFS= read -r line; do
      [[ "$line" =~ ^#|^[[:space:]]*$ ]] && continue
      EXEMPT_SET+=("$(echo "$line" | awk '{print $1}')")
    done < "$EXEMPT_FILE"
  fi

  is_exempt() {
    local name="$1"
    for e in "${EXEMPT_SET[@]:-}"; do
      [[ "$e" == "$name" ]] && return 0
    done
    return 1
  }

  # Check 1: every hooks/*.sh is in base.json OR exempt
  for hookfile in "$REPO_ROOT/hooks/"*.sh; do
    [[ -f "$hookfile" ]] || continue
    name=$(basename "$hookfile")
    if ! grep -q "$name" "$BASE_JSON" && ! is_exempt "$name"; then
      TYPE_A_GAPS+=("hooks/$name")
    fi
  done

  # Check 2: every hooks/*.sh reference in base.json actually exists
  while IFS= read -r ref; do
    if [[ ! -f "$REPO_ROOT/$ref" ]]; then
      TYPE_A_DANGLING+=("$ref (referenced in base.json but file missing)")
    fi
  done < <(python3 -c "
import json, re, sys
data = json.load(open('$BASE_JSON'))
refs = set()
def walk(obj):
    if isinstance(obj, dict):
        cmd = obj.get('command', '')
        for m in re.findall(r'hooks/[\w.-]+\.sh', cmd):
            refs.add(m)
        for v in obj.values():
            walk(v)
    elif isinstance(obj, list):
        for i in obj: walk(i)
walk(data)
print('\n'.join(sorted(refs)))
" 2>/dev/null)

fi

# ── Type B: I/O contract coverage ───────────────────────────────────────────

if [[ "$CHECK_TYPE_B" == "true" && -f "$IO_CONTRACTS" ]]; then

  # Parse contracts file: FORMAT per line:
  #   SCRIPT  WRITES  path/to/file.jsonl
  #   SCRIPT  READS   path/to/file.jsonl
  # Check: every WRITES has a matching READS (and vice versa).

  declare -A WRITE_PATHS
  declare -A READ_PATHS

  while IFS= read -r line; do
    [[ "$line" =~ ^#|^[[:space:]]*$ ]] && continue
    script=$(echo "$line" | awk '{print $1}')
    direction=$(echo "$line" | awk '{print $2}')
    path=$(echo "$line" | awk '{print $3}')
    [[ -z "$path" || -z "$direction" ]] && continue

    case "$direction" in
      WRITES) WRITE_PATHS["$path"]+="$script " ;;
      READS)  READ_PATHS["$path"]+="$script " ;;
    esac
  done < "$IO_CONTRACTS"

  # Find paths that are WRITTEN but never READ (dead ends)
  for path in "${!WRITE_PATHS[@]}"; do
    if [[ -z "${READ_PATHS[$path]:-}" ]]; then
      TYPE_B_GAPS+=("DEAD END: ${WRITE_PATHS[$path]}writes '$path' but no consumer reads it")
    fi
  done

  # Find paths that are READ but never WRITTEN (broken source)
  for path in "${!READ_PATHS[@]}"; do
    if [[ -z "${WRITE_PATHS[$path]:-}" ]]; then
      TYPE_B_GAPS+=("BROKEN SOURCE: ${READ_PATHS[$path]}reads '$path' but no producer writes it")
    fi
  done

elif [[ "$CHECK_TYPE_B" == "true" && ! -f "$IO_CONTRACTS" ]]; then
  WARNINGS+=("cl-io-contracts.txt not found — Type B check skipped. Create scripts/cl-io-contracts.txt to enable.")
fi

# ── Output ───────────────────────────────────────────────────────────────────

TOTAL_GAPS=$(( ${#TYPE_A_GAPS[@]} + ${#TYPE_A_DANGLING[@]} + ${#TYPE_B_GAPS[@]} ))

if [[ "$JSON_OUTPUT" == "true" ]]; then
  # Write each array to a temp file to avoid quoting/escape issues at the shell→Python boundary.
  # Gap descriptions may contain arbitrary paths, quotes, and backslashes.
  _TMP_DIR=$(mktemp -d)
  printf '%s\n' "${TYPE_A_GAPS[@]:-}"    > "$_TMP_DIR/a_unwired.txt"
  printf '%s\n' "${TYPE_A_DANGLING[@]:-}" > "$_TMP_DIR/a_dangling.txt"
  printf '%s\n' "${TYPE_B_GAPS[@]:-}"    > "$_TMP_DIR/b.txt"
  printf '%s\n' "${WARNINGS[@]:-}"       > "$_TMP_DIR/warnings.txt"
  python3 - "$_TMP_DIR" "$TOTAL_GAPS" << 'PYEOF'
import json, sys, pathlib
d = pathlib.Path(sys.argv[1])
def read_lines(f):
    return [l for l in (d / f).read_text().splitlines() if l.strip()]
print(json.dumps({
  "type_a_unwired":  read_lines("a_unwired.txt"),
  "type_a_dangling": read_lines("a_dangling.txt"),
  "type_b":          read_lines("b.txt"),
  "warnings":        read_lines("warnings.txt"),
  "total_gaps":      int(sys.argv[2]),
}, indent=2))
PYEOF
  rm -rf "$_TMP_DIR"
else
  echo "=== LOOP Wire Audit ==="
  echo ""

  if [[ ${#TYPE_A_GAPS[@]} -gt 0 ]]; then
    echo "TYPE A — Unwired hooks (exist but not in base.json):"
    for gap in "${TYPE_A_GAPS[@]}"; do
      echo "  ✗ $gap"
    done
    echo "  → Add to base.json OR add to hooks/exempt.txt with reason."
    echo ""
  fi

  if [[ ${#TYPE_A_DANGLING[@]} -gt 0 ]]; then
    echo "TYPE A — Dangling references (base.json references missing files):"
    for gap in "${TYPE_A_DANGLING[@]}"; do
      echo "  ✗ $gap"
    done
    echo ""
  fi

  if [[ ${#TYPE_B_GAPS[@]} -gt 0 ]]; then
    echo "TYPE B — Broken I/O contracts:"
    for gap in "${TYPE_B_GAPS[@]}"; do
      echo "  ✗ $gap"
    done
    echo ""
  fi

  if [[ ${#WARNINGS[@]} -gt 0 ]]; then
    for w in "${WARNINGS[@]}"; do
      echo "  ⚠ $w"
    done
    echo ""
  fi

  if [[ "$TOTAL_GAPS" -eq 0 ]]; then
    echo "  ✓ All hooks wired. All I/O contracts satisfied."
  else
    echo "TOTAL: $TOTAL_GAPS gap(s) found"
  fi
fi

exit $(( TOTAL_GAPS > 0 ? 1 : 0 ))
